---
title: "Cancer Data"
author: "Parth Pandit"
date: "2022-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(class)
library(caret)
library(gmodels)
library(ROCR)
#Do some cross validation for the first level models 
```


## Cleaning the data
```{r}
cancer = read.csv("wisc.csv")
cancer$id = NULL
cancer$diagnosis = as.factor(cancer$diagnosis)
str(cancer)
summary(cancer)
```

## Getting the data ready for analysis
```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

cancermm <- as.data.frame(model.matrix(~.-1,cancer))

# Randomize the rows in the data (shuffling the rows)
set.seed(0)
cancer_random <- cancermm[sample(nrow(cancermm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
cancer_norm <- as.data.frame(lapply(cancer_random, normalize))
str(cancer_norm)
```

## Getting Train and Test Samples

```{r}
# Selects 10000 random rows for test data
test_set <- sample(1:nrow(cancer_norm), 285) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors 
train <- cancer_norm[-test_set,]
test <- cancer_norm[test_set,]

train_labels <- cancer_norm[-test_set, "diagnosisM"]
test_labels <- cancer_norm[test_set, "diagnosisM"]
```

## THE LOG MODEL

```{r}
str(train)
```


```{r}
train$diagnosisB = NULL
test$diagnosisB = NULL
```


```{r}
set.seed(0)



ctrl = trainControl(method = "cv",
                    number = 4)

logmodel = train(diagnosis ~., method = "multinom",
                 data = cancer,
                 trControl = ctrl)

summary(logmodel)
```

#Decision Tree
```{r}

ctrl <- trainControl(method = "cv", number = 10,
                     selectionFunction = "oneSE")

# use expand.grid() to create grid of tuning parameters
grid <- expand.grid(.model = "tree",
                    .trials = c(1, 5, 10, 15, 20, 25, 30, 35),
                    .winnow = "FALSE")

# look at the result of expand.grid()
grid

# customize train() with the control list and grid of parameters 
set.seed(300)
dt <- train(diagnosis ~ ., data = cancer, method = "C5.0",
           metric = "Kappa",
           trControl = ctrl,
           tuneGrid = grid)
dt



```


